version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  bank-webhook:
    build:
      context: .
      dockerfile: ./docker/bank-webhook.Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:mysecretpassword@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy

  user-app:
    build:
      context: .
      dockerfile: ./docker/user-app.Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:mysecretpassword@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: